"""QRCode model added

Revision ID: 251abd473797
Revises: c34a91db9bd2
Create Date: 2024-05-18 18:30:35.554564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251abd473797'
down_revision: Union[str, None] = 'c34a91db9bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('qr_code', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_codes')
    # ### end Alembic commands ###
