"""Cascade deletion for photo relations added

Revision ID: 3019bc5f8124
Revises: c4471cb7cc11
Create Date: 2024-05-19 22:19:54.139080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3019bc5f8124'
down_revision: Union[str, None] = 'c4471cb7cc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_photo_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'photos', ['photo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('phototags_photo_id_fkey', 'phototags', type_='foreignkey')
    op.create_foreign_key(None, 'phototags', 'photos', ['photo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('qr_codes_photo_id_fkey', 'qr_codes', type_='foreignkey')
    op.create_foreign_key(None, 'qr_codes', 'photos', ['photo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qr_codes', type_='foreignkey')
    op.create_foreign_key('qr_codes_photo_id_fkey', 'qr_codes', 'photos', ['photo_id'], ['id'])
    op.drop_constraint(None, 'phototags', type_='foreignkey')
    op.create_foreign_key('phototags_photo_id_fkey', 'phototags', 'photos', ['photo_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_photo_id_fkey', 'comments', 'photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###
