"""I changed schemas

Revision ID: 64da0241a576
Revises: 75b905aed1e1
Create Date: 2024-05-20 12:27:08.850869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64da0241a576'
down_revision: Union[str, None] = '75b905aed1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=13), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    # ### end Alembic commands ###
