"""Asset type added to photo

Revision ID: c34a91db9bd2
Revises: 2b0077df03df
Create Date: 2024-05-18 16:10:45.557629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c34a91db9bd2'
down_revision: Union[str, None] = '2b0077df03df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the ENUM type
asset_type_enum = postgresql.ENUM('origin', 'avatar', 'greyscale', 'delete_bg', 'oil_paint', 'sepia', 'outline', name='assettype', create_type=False)

def upgrade() -> None:
    asset_type_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('asset_type', asset_type_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'asset_type')
    # ### end Alembic commands ###
