"""I changed blacklist

Revision ID: c7f40aa10815
Revises: c34a91db9bd2
Create Date: 2024-05-18 11:44:38.959230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f40aa10815'
down_revision: Union[str, None] = 'c34a91db9bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist_tokens', sa.Column('blacklisted_on', sa.DateTime(), nullable=True))
    op.alter_column('blacklist_tokens', 'token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_index('ix_blacklist_tokens_id', table_name='blacklist_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_blacklist_tokens_id', 'blacklist_tokens', ['id'], unique=False)
    op.alter_column('blacklist_tokens', 'token',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('blacklist_tokens', 'blacklisted_on')
    # ### end Alembic commands ###
