"""I returned schemas

Revision ID: d5b76df8c912
Revises: 660ec0712591
Create Date: 2024-05-20 14:37:38.250640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b76df8c912'
down_revision: Union[str, None] = '660ec0712591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=13), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
